# Generated by Django 4.1.7 on 2023-03-29 14:36

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer', max_length=150, unique=True, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('profile_picture', models.ImageField(default='profile_pictures/default/tutor.jpg', null=True, upload_to=accounts.models.upload_image_path, verbose_name='User Picture')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='contact number')),
                ('bio', models.TextField(blank=True, max_length=999999, verbose_name='bio which also houses the lessons')),
                ('active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('student', models.BooleanField(default=False, help_text='Categorizes the user as student', verbose_name='Student')),
                ('tutor', models.BooleanField(default=False, help_text='Categorizes the user as tutor', verbose_name='Tutor')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('numReviews', models.IntegerField(blank=True, null=True, verbose_name='reviews')),
                ('meeting_link', models.TextField(blank=True, null=True, verbose_name='Zoom Link')),
                ('price_rate_hour', models.DecimalField(decimal_places=0, max_digits=3, null=True, verbose_name='Hourly Price Rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartSchedule',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('meeting_link', models.TextField(blank=True, null=True, verbose_name='Zoom Link')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_title', models.TextField(max_length=100)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('date', models.CharField(max_length=50, verbose_name='Day to be scheduled')),
                ('count_in_stock_hour', models.PositiveIntegerField(verbose_name='How many slots of hours available?')),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartScheduleItem',
            fields=[
                ('name', models.CharField(blank=True, help_text='Cart Item Name', max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, default=0, help_text='Quantity of Hour', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price from the Product', max_digits=12, null=True)),
                ('image', models.CharField(blank=True, help_text='Image URL', max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(help_text='From the cart', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.cartschedule')),
                ('product', models.ForeignKey(help_text='Schedule Date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subject'),
        ),
    ]
