# Generated by Django 4.1.5 on 2023-03-31 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=300, null=True)),
                ('concern', models.TextField(blank=True, max_length=300, null=True)),
                ('comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
