# Generated by Django 4.1.7 on 2023-03-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
