# Generated by Django 4.1.7 on 2023-04-05 15:58

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderschedule',
            old_name='createdAt',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='orderschedule',
            old_name='paidAt',
            new_name='paid_date',
        ),
        migrations.RenameField(
            model_name='orderschedule',
            old_name='isPaid',
            new_name='paid_status',
        ),
        migrations.RenameField(
            model_name='orderschedule',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='orderschedule',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='orderscheduleitem',
            old_name='product',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='createdAt',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_student',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='user_tutor',
        ),
        migrations.RemoveField(
            model_name='orderschedule',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Who ordered?'),
        ),
        migrations.AlterField(
            model_name='orderscheduleitem',
            name='image',
            field=models.ImageField(default='profile_pictures/default/tutor.jpg', null=True, upload_to=accounts.models.upload_image_path, verbose_name='User Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_rate_hour',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Hourly Price Rate'),
        ),
    ]
