# Generated by Django 4.1.5 on 2023-03-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subject_name',
        ),
    ]
