# Generated by Django 4.1.7 on 2023-04-06 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='count_in_stock',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(24)]),
        ),
    ]
