# Generated by Django 4.1.5 on 2023-03-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_product_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate_hour',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
