# Generated by Django 4.1.5 on 2023-04-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_contact_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
