# Generated by Django 4.1.5 on 2023-04-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contact_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='done',
        ),
    ]
