# Generated by Django 4.2 on 2023-04-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_photo_education_backend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleorder',
            name='message',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Message to Tutor'),
        ),
    ]
