# Generated by Django 4.2 on 2023-04-21 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_scheduleorder_tutor_alter_scheduleorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleorder',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_on_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduleorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
