# Generated by Django 4.2 on 2023-04-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_scheduleorder_tutor_alter_scheduleorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer', max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
    ]
