# Generated by Django 4.1.5 on 2023-04-21 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleorder',
            name='tutor',
        ),
        migrations.AlterField(
            model_name='scheduleorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
