export const CONTACT_ADD_REQUEST = 'CONTACT_ADD_REQUEST'
export const CONTACT_ADD_SUCCESS = 'CONTACT_ADD_SUCCESS'
export const CONTACT_ADD_FAIL = 'CONTACT_ADD_FAIL'
export const CONTACT_ADD_RESET = 'CONTACT_ADD_RESET'

export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST'
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS'
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL'

export const CONTACT_DETAILS_REQUEST = 'CONTACT_DETAILS_REQUEST'
export const CONTACT_DETAILS_SUCCESS = 'CONTACT_DETAILS_SUCCESS'
export const CONTACT_DETAILS_FAIL = 'CONTACT_DETAILS_FAIL'


export const CONTACT_UPDATE_REQUEST = "CONTACT_UPDATE_REQUEST";
export const CONTACT_UPDATE_SUCCESS = "CONTACT_UPDATE_SUCCESS";
export const CONTACT_UPDATE_FAIL = "CONTACT_UPDATE_FAIL";
export const CONTACT_UPDATE_RESET = "CONTACT_UPDATE_RESET";

export const SUBJECT_ADD_REQUEST = 'SUBJECT_ADD_REQUEST'
export const SUBJECT_ADD_SUCCESS = 'SUBJECT_ADD_SUCCESS'
export const SUBJECT_ADD_FAIL = 'SUBJECT_ADD_FAIL'
export const SUBJECT_ADD_RESET = 'SUBJECT_ADD_RESET'