export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST'
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS'
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL'

export const REVIEW_LIST_TUTOR_REQUEST = 'REVIEW_LIST_TUTOR_REQUEST'
export const REVIEW_LIST_TUTOR_SUCCESS = 'REVIEW_LIST_TUTOR_SUCCESS'
export const REVIEW_LIST_TUTOR_FAIL = 'REVIEW_LIST_TUTOR_FAIL'


export const REVIEW_DETAIL_REQUEST = 'REVIEW_DETAIL_REQUEST'
export const REVIEW_DETAIL_SUCCESS = 'REVIEW_DETAIL_SUCCESS'
export const REVIEW_DETAIL_FAIL = 'REVIEW_DETAIL_FAIL'


export const REVIEW_ADD_REQUEST = 'REVIEW_ADD_REQUEST'
export const REVIEW_ADD_SUCCESS = 'REVIEW_ADD_SUCCESS'
export const REVIEW_ADD_FAIL = 'REVIEW_ADD_FAIL'
export const REVIEW_ADD_RESET = 'REVIEW_ADD_RESET'


export const REVIEW_EDIT_REQUEST = 'REVIEW_EDIT_REQUEST'
export const REVIEW_EDIT_SUCCESS = 'REVIEW_EDIT_SUCCESS'
export const REVIEW_EDIT_FAIL = 'REVIEW_EDIT_FAIL'
export const REVIEW_EDIT_RESET = 'REVIEW_EDIT_RESET'
