export const SCHEDULE_CART_ADD_ITEM = 'SCHEDULE_CART_ADD_ITEM'
export const SCHEDULE_CART_REMOVE_ITEM = 'SCHEDULE_CART_REMOVE_ITEM'
export const SCHEDULE_CART_RESET = 'SCHEDULE_CART_RESET'

export const SCHEDULE_CART_SAVE_PAYMENT_METHOD = 'SCHEDULE_CART_SAVE_PAYMENT_METHOD'