export const SCHEDULE_ORDER_MY_LIST_REQUEST = 'SCHEDULE_ORDER_MY_LIST_REQUEST'
export const SCHEDULE_ORDER_MY_LIST_SUCCESS = 'SCHEDULE_ORDER_MY_LIST_SUCCESS'
export const SCHEDULE_ORDER_MY_LIST_FAIL = 'SCHEDULE_ORDER_MY_LIST_FAIL'


export const SCHEDULE_ORDER_DETAILS_REQUEST = 'SCHEDULE_ORDER_DETAILS_REQUEST'
export const SCHEDULE_ORDER_DETAILS_SUCCESS = 'SCHEDULE_ORDER_DETAILS_SUCCESS'
export const SCHEDULE_ORDER_DETAILS_FAIL = 'SCHEDULE_ORDER_DETAILS_FAIL'


export const SCHEDULE_ORDER_PAY_REQUEST = 'SCHEDULE_ORDER_PAY_REQUEST'
export const SCHEDULE_ORDER_PAY_SUCCESS = 'SCHEDULE_ORDER_PAY_SUCCESS'
export const SCHEDULE_ORDER_PAY_FAIL = 'SCHEDULE_ORDER_PAY_FAIL'
export const SCHEDULE_ORDER_PAY_RESET = 'SCHEDULE_ORDER_PAY_RESET'