export const SCHEDULE_LIST_REQUEST = 'SCHEDULE_LIST_REQUEST'
export const SCHEDULE_LIST_SUCCESS = 'SCHEDULE_LIST_SUCCESS'
export const SCHEDULE_LIST_FAIL = 'SCHEDULE_LIST_FAIL'

export const SCHEDULE_DETAILS_REQUEST = 'SCHEDULE_DETAILS_REQUEST'
export const SCHEDULE_DETAILS_SUCCESS = 'SCHEDULE_DETAILS_SUCCESS'
export const SCHEDULE_DETAILS_FAIL = 'SCHEDULE_DETAILS_FAIL'

export const SCHEDULE_ADD_REQUEST = 'SCHEDULE_ADD_REQUEST'
export const SCHEDULE_ADD_SUCCESS = 'SCHEDULE_ADD_REQUEST'
export const SCHEDULE_ADD_FAIL = 'SCHEDULE_ADD_REQUEST'