
export const SUBJECT_ADD_REQUEST = 'SUBJECT_ADD_REQUEST'
export const SUBJECT_ADD_SUCCESS = 'SUBJECT_ADD_SUCCESS'
export const SUBJECT_ADD_FAIL = 'SUBJECT_ADD_FAIL'
export const SUBJECT_ADD_RESET = 'SUBJECT_ADD_RESET'

export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST'
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS'
export const SUBJECT_LIST_FAIL = 'SUBJECT_LIST_FAIL'

export const SUBJECT_DETAILS_REQUEST = 'SUBJECT_DETAILS_REQUEST'
export const SUBJECT_DETAILS_SUCCESS = 'SUBJECT_DETAILS_SUCCESS'
export const SUBJECT_DETAILS_FAIL = 'SUBJECT_DETAILS_FAIL'

export const SUBJECT_UPDATE_REQUEST = "SUBJECT_UPDATE_REQUEST";
export const SUBJECT_UPDATE_SUCCESS = "SUBJECT_UPDATE_SUCCESS";
export const SUBJECT_UPDATE_FAIL = "SUBJECT_UPDATE_FAIL";
export const SUBJECT_UPDATE_RESET = "SUBJECT_UPDATE_RESET";


export const SUBJECT_DELETE_REQUEST = "SUBJECT_DELETE_REQUEST";
export const SUBJECT_DELETE_SUCCESS = "SUBJECT_DELETE_SUCCESS";
export const SUBJECT_DELETE_FAIL = "SUBJECT_DELETE_FAIL";
export const SUBJECT_DELETE_RESET = "SUBJECT_DELETE_RESET";

export const SUBJECT_TUTOR_LIST_REQUEST = 'SUBJECT_TUTOR_LIST_REQUEST'
export const SUBJECT_TUTOR_LIST_SUCCESS = 'SUBJECT_TUTOR_LIST_SUCCESS'
export const SUBJECT_TUTOR_LIST_FAIL = 'SUBJECT_LIST_FAIL'