export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST'
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS'
export const SUBJECT_LIST_FAIL = 'SUBJECT_LIST_FAIL'

export const SUBJECT_DETAILS_REQUEST = 'SUBJECT_DETAILS_REQUEST'
export const SUBJECT_DETAILS_SUCCESS = 'SUBJECT_DETAILS_SUCCESS'
export const SUBJECT_DETAILS_FAIL = 'SUBJECT_DETAILS_FAIL'

