export const TUTOR_LIST_REQUEST = 'TUTOR_LIST_REQUEST'
export const TUTOR_LIST_SUCCESS = 'TUTOR_LIST_SUCCESS'
export const TUTOR_LIST_FAIL = 'TUTOR_LIST_FAIL'

export const TUTOR_DETAILS_REQUEST = 'TUTOR_DETAILS_REQUEST'
export const TUTOR_DETAILS_SUCCESS = 'TUTOR_DETAILS_SUCCESS'
export const TUTOR_DETAILS_FAIL = 'TUTOR_DETAILS_FAIL'

export const TUTOR_CREATE_REVIEW_REQUEST = 'TUTOR_CREATE_REVIEW_REQUEST'
export const TUTOR_CREATE_REVIEW_SUCCESS = 'TUTOR_CREATE_REVIEW_SUCCESS'
export const TUTOR_CREATE_REVIEW_FAIL = 'TUTOR_CREATE_REVIEW_FAIL'
export const TUTOR_CREATE_REVIEW_RESET = 'TUTOR_CREATE_REVIEW_RESET'

export const ADMIN_LIST_REQUEST = 'ADMIN_LIST_REQUEST'
export const ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCCESS'
export const ADMIN_LIST_FAIL = 'ADMIN_LIST_FAIL'

export const TUTOR_UPDATE_REQUEST = "TUTOR_UPDATE_REQUEST";
export const TUTOR_UPDATE_SUCCESS = "TUTOR_UPDATE_SUCCESS";
export const TUTOR_UPDATE_FAIL = "TUTOR_UPDATE_FAIL";
export const TUTOR_UPDATE_RESET = "TUTOR_UPDATE_RESET";



export const MY_STUDENTS_LIST_REQUEST = 'MY_STUDENTS_LIST_REQUEST'
export const MY_STUDENTS_LIST_SUCCESS = 'MY_STUDENTS_LIST_SUCCESS'
export const MY_STUDENTS_LIST_FAIL = 'MY_STUDENTS_LIST_FAIL'
export const MY_STUDENTS_LIST_RESET = 'MY_STUDENTS_LIST_RESET'



export const STUDENT_ORDER_DETAILS_REQUEST = 'STUDENT_ORDER_DETAILS_REQUEST'
export const STUDENT_ORDER_DETAILS_SUCCESS = 'STUDENT_ORDER_DETAILS_SUCCESS'
export const STUDENT_ORDER_DETAILS_FAIL = 'STUDENT_ORDER_DETAILS_FAIL'
export const STUDENT_ORDER_DETAILS_RESET = 'STUDENT_ORDER_DETAILS_RESET'