export const TUTOR_LIST_REQUEST = 'TUTOR_LIST_REQUEST'
export const TUTOR_LIST_SUCCESS = 'TUTOR_LIST_SUCCESS'
export const TUTOR_LIST_FAIL = 'TUTOR_LIST_FAIL'

export const TUTOR_DETAILS_REQUEST = 'TUTOR_DETAILS_REQUEST'
export const TUTOR_DETAILS_SUCCESS = 'TUTOR_DETAILS_SUCCESS'
export const TUTOR_DETAILS_FAIL = 'TUTOR_DETAILS_FAIL'